# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [ (modulesPath + "/installer/scan/not-detected.nix") ];

  boot.initrd.availableKernelModules =
    [ "xhci_pci" "ahci" "nvme" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "wl" ];
  boot.extraModprobeConfig = ''
    options snd slots=snd-hda-nvidia
  '';
  fileSystems."/" = {
    device = "/dev/disk/by-uuid/11987c8e-6adc-4664-a92d-a3bcd98a28ba";
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/B55E-A2BF";
    fsType = "vfat";
  };

  fileSystems."/media" = {
    device = "/dev/disk/by-label/media";
    fsType = "ext4";
  };

  fileSystems."/backup" = {
    device = "/dev/disk/by-label/backup";
    fsType = "ext4";
  };

  swapDevices =
    [{ device = "/dev/disk/by-uuid/7ad126d7-2de9-4e63-a7cc-66da281bc3da"; }];

  sound.enable = true;
  hardware.bluetooth.enable = true;
  hardware.pulseaudio = {
    enable = true;
    support32Bit = true;
    extraConfig = ''
      load-module module-native-protocol-tcp auth-ip-acl=127.0.0.1
       load-module module-switch-on-connect''; # Needed by mpd to be able to use Pulseaudio
  };

  powerManagement = {
    enable = true;
    cpuFreqGovernor = lib.mkDefault "powersave";
  };
  # high-resolution display
  hardware.video.hidpi.enable = lib.mkDefault true;
}
